version: '3.4'
networks:
  obank-network:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/16

services:
  #Kafka
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:5.1.2
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  # broker:
  #   image: confluentinc/cp-enterprise-kafka:5.1.2
  #   hostname: broker
  #   container_name: broker
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #     - "29092:29092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
  #     CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  #     CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  #     CONFLUENT_METRICS_ENABLE: 'true'
  #     CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:5.1.2
  #   hostname: schema-registry
  #   container_name: schema-registry
  #   depends_on:
  #     - zookeeper
  #     - broker
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  #Customer
  customer.data:
    build:
      context: services/Customer.API/.
      dockerfile: Docker.Customer.Data.MSSql.WithData.Dockerfile
    ports:
      - '5101:1433'
    networks:
      obank-network:
        ipv4_address: 10.20.30.101
  customer.api:
    build:
      context: services/Customer.API/.
      dockerfile: Docker.Customer.API.DotNetCore.WebAPI.Dockerfile
    ports:
      - '5151:80'
    depends_on:
      - customer.data
    environment:
      - RUNNING_ENVIRONMENT=Docker
    networks:
      obank-network:
        ipv4_address: 10.20.30.151





  
