package com.deposit;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class DepositAPIApplication {

	public static void main(String[] args) {
		SpringApplication.run(DepositAPIApplication.class, args);
	}

}
Docker.Deposit.Data.MySql.WithData.Dockerfile
# Derived from official mysql image (our base image)
FROM mysql:latest

# Add a database
ENV MYSQL_ROOT_PASSWORD Strong_Passw0rd 
ENV MYSQL_DATABASE company

# COPY ./src/main/java/com/deposit/infrastructure/dataseeds/data-seed.csv /var/lib/mysql
COPY ./src/main/java/com/deposit/infrastructure/dataseeds/data-seed.sql /docker-entrypoint-initdb.d/

version: "3.4"
services:
  customer.data.mssql:
    build:
      context: .
      dockerfile: Docker.Deposit.Data.MySql.WithData.Dockerfile
    ports:
      - "3306:3306"

	      SET GLOBAL local_infile = 1;

CREATE TABLE employees (
first_name varchar(100),
last_name  varchar(100)
);

insert into employees (first_name, last_name) values ('Georgeanne', 'Catmull');
insert into employees (first_name, last_name) values ('Law', 'Slisby');
insert into employees (first_name, last_name) values ('Micheal', 'MacColgan');
insert into employees (first_name, last_name) values ('Jeremie', 'Lowsely');
insert into employees (first_name, last_name) values ('Cleveland', 'Zealander');
insert into employees (first_name, last_name) values ('Adi', 'Carbery');
insert into employees (first_name, last_name) values ('Milt', 'Tamburo');
insert into employees (first_name, last_name) values ('Meara', 'Woodroffe');
insert into employees (first_name, last_name) values ('Javier', 'Minghi');
insert into employees (first_name, last_name) values ('Birgit', 'Towsey');
insert into employees (first_name, last_name) values ('Cher', 'Valentinuzzi');
insert into employees (first_name, last_name) values ('Fania', 'Sleeny');
insert into employees (first_name, last_name) values ('Karolina', 'Lingfoot');
insert into employees (first_name, last_name) values ('Magnum', 'Gonin');
insert into employees (first_name, last_name) values ('Trudi', 'Pasque');
insert into employees (first_name, last_name) values ('Lizabeth', 'Clare');
insert into employees (first_name, last_name) values ('Denny', 'Brigman');
insert into employees (first_name, last_name) values ('Mathian', 'Enderson');
insert into employees (first_name, last_name) values ('Glenine', 'Warsap');
insert into employees (first_name, last_name) values ('Addison', 'Esome');
insert into employees (first_name, last_name) values ('Louisette', 'Christene');
insert into employees (first_name, last_name) values ('Jimmie', 'Robken');
insert into employees (first_name, last_name) values ('Danya', 'Pardie');
insert into employees (first_name, last_name) values ('Alvis', 'Hearsum');
insert into employees (first_name, last_name) values ('Duffie', 'Binks');
insert into employees (first_name, last_name) values ('Dasi', 'Mouan');
insert into employees (first_name, last_name) values ('Godart', 'Palk');
insert into employees (first_name, last_name) values ('Joye', 'Oley');
insert into employees (first_name, last_name) values ('Nikola', 'Lammenga');
insert into employees (first_name, last_name) values ('Nial', 'Crippell');
insert into employees (first_name, last_name) values ('Lauritz', 'Duthie');
insert into employees (first_name, last_name) values ('Sinclare', 'Blown');
insert into employees (first_name, last_name) values ('Maddy', 'Manford');
insert into employees (first_name, last_name) values ('Marianne', 'Rodnight');
insert into employees (first_name, last_name) values ('Hilda', 'Samples');
insert into employees (first_name, last_name) values ('Blinny', 'Wellington');
insert into employees (first_name, last_name) values ('Juieta', 'Geffen');
insert into employees (first_name, last_name) values ('Erskine', 'Thow');
insert into employees (first_name, last_name) values ('Atlanta', 'Elgy');
insert into employees (first_name, last_name) values ('Starlene', 'Sailor');
insert into employees (first_name, last_name) values ('Noelle', 'Arnatt');
insert into employees (first_name, last_name) values ('Aurel', 'Tieman');
insert into employees (first_name, last_name) values ('Malina', 'Moogan');
insert into employees (first_name, last_name) values ('Aurie', 'Bruckmann');
insert into employees (first_name, last_name) values ('Wini', 'Bleackly');
insert into employees (first_name, last_name) values ('Napoleon', 'Picken');
insert into employees (first_name, last_name) values ('Claudian', 'Barbosa');
insert into employees (first_name, last_name) values ('Anastasie', 'McCumesky');
insert into employees (first_name, last_name) values ('Nickola', 'Shoebrook');
insert into employees (first_name, last_name) values ('Blakelee', 'Santora');
insert into employees (first_name, last_name) values ('Milton', 'Dassindale');
insert into employees (first_name, last_name) values ('Lesly', 'Port');
insert into employees (first_name, last_name) values ('Zach', 'Rollitt');
insert into employees (first_name, last_name) values ('Alexa', 'Garrattley');
insert into employees (first_name, last_name) values ('Cherry', 'Fauning');
insert into employees (first_name, last_name) values ('Morty', 'Roust');
insert into employees (first_name, last_name) values ('Sharline', 'Guiness');
insert into employees (first_name, last_name) values ('Morlee', 'Brikner');
insert into employees (first_name, last_name) values ('Lowe', 'Reid');
insert into employees (first_name, last_name) values ('Dore', 'Leech');
insert into employees (first_name, last_name) values ('Matthaeus', 'Soughton');
insert into employees (first_name, last_name) values ('Alain', 'Fattorini');
insert into employees (first_name, last_name) values ('Katinka', 'Kempton');
insert into employees (first_name, last_name) values ('Cory', 'Heindrich');
insert into employees (first_name, last_name) values ('Peggi', 'McInility');
insert into employees (first_name, last_name) values ('Elsey', 'Weavers');
insert into employees (first_name, last_name) values ('Andree', 'Wombwell');
insert into employees (first_name, last_name) values ('Edward', 'Eltringham');
insert into employees (first_name, last_name) values ('Mick', 'Salazar');
insert into employees (first_name, last_name) values ('Heath', 'Brunker');
insert into employees (first_name, last_name) values ('Raimund', 'Goodanew');
insert into employees (first_name, last_name) values ('Bail', 'Tunno');
insert into employees (first_name, last_name) values ('Galvin', 'Impy');
insert into employees (first_name, last_name) values ('Amber', 'Croxall');
insert into employees (first_name, last_name) values ('Leslie', 'Tippings');
insert into employees (first_name, last_name) values ('Ralph', 'Lomond');
insert into employees (first_name, last_name) values ('Othilia', 'Tilmouth');
insert into employees (first_name, last_name) values ('Dalila', 'Caston');
insert into employees (first_name, last_name) values ('Barron', 'Jovis');
insert into employees (first_name, last_name) values ('Jeno', 'O''Neill');
insert into employees (first_name, last_name) values ('Marj', 'Kenworthy');
insert into employees (first_name, last_name) values ('Jorgan', 'Roblin');
insert into employees (first_name, last_name) values ('Margie', 'Biagi');
insert into employees (first_name, last_name) values ('Bette', 'Kildale');
insert into employees (first_name, last_name) values ('Corenda', 'Kleinmintz');
insert into employees (first_name, last_name) values ('Arturo', 'Goroni');
insert into employees (first_name, last_name) values ('Rossy', 'Carcas');
insert into employees (first_name, last_name) values ('Ange', 'Syder');
insert into employees (first_name, last_name) values ('Farly', 'Haizelden');
insert into employees (first_name, last_name) values ('Stacee', 'Lowndes');
insert into employees (first_name, last_name) values ('Sergent', 'Absolem');
insert into employees (first_name, last_name) values ('Wallache', 'Blackey');
insert into employees (first_name, last_name) values ('Max', 'Simmins');
insert into employees (first_name, last_name) values ('Pauline', 'Davidovich');
insert into employees (first_name, last_name) values ('Berkeley', 'Cardow');
insert into employees (first_name, last_name) values ('Carmine', 'Chase');
insert into employees (first_name, last_name) values ('Othelia', 'Normanvell');
insert into employees (first_name, last_name) values ('Beauregard', 'Pacht');
insert into employees (first_name, last_name) values ('Yvor', 'Wallsworth');
insert into employees (first_name, last_name) values ('Artair', 'Nickerson');
insert into employees (first_name, last_name) values ('Laurie', 'Poytress');
insert into employees (first_name, last_name) values ('Merna', 'Bach');
insert into employees (first_name, last_name) values ('Elinore', 'Cettell');
insert into employees (first_name, last_name) values ('Cherri', 'Pawels');
insert into employees (first_name, last_name) values ('Courtney', 'Exrol');
insert into employees (first_name, last_name) values ('Magdaia', 'Hadingham');
insert into employees (first_name, last_name) values ('Ben', 'Probart');
insert into employees (first_name, last_name) values ('Orin', 'Levitt');
insert into employees (first_name, last_name) values ('Marrissa', 'Gillise');
insert into employees (first_name, last_name) values ('Carmella', 'Burn');
insert into employees (first_name, last_name) values ('Gerry', 'Burbudge');
insert into employees (first_name, last_name) values ('Odette', 'Merrgan');
insert into employees (first_name, last_name) values ('Krystle', 'Postlewhite');
insert into employees (first_name, last_name) values ('Adrien', 'Rosen');
insert into employees (first_name, last_name) values ('Devan', 'Sives');
insert into employees (first_name, last_name) values ('Gilli', 'Leckey');
insert into employees (first_name, last_name) values ('Rosalyn', 'Kliement');
insert into employees (first_name, last_name) values ('Ema', 'Schroter');
insert into employees (first_name, last_name) values ('Aldwin', 'Websdale');
insert into employees (first_name, last_name) values ('Victoir', 'Mallinson');
insert into employees (first_name, last_name) values ('Robyn', 'Hancill');
insert into employees (first_name, last_name) values ('Lishe', 'Braunton');
insert into employees (first_name, last_name) values ('Alison', 'Pauleau');
insert into employees (first_name, last_name) values ('Babs', 'Bedow');
insert into employees (first_name, last_name) values ('Mary', 'Saffin');
insert into employees (first_name, last_name) values ('Jennee', 'Huckfield');
insert into employees (first_name, last_name) values ('Kirby', 'Gummery');
insert into employees (first_name, last_name) values ('Augustina', 'Hagston');
insert into employees (first_name, last_name) values ('Guendolen', 'Bingley');
insert into employees (first_name, last_name) values ('Georgena', 'Boniface');
insert into employees (first_name, last_name) values ('Bettine', 'Chellenham');
insert into employees (first_name, last_name) values ('Constantina', 'Deppen');
insert into employees (first_name, last_name) values ('Kort', 'Ballsdon');
insert into employees (first_name, last_name) values ('Jacquie', 'Pund');
insert into employees (first_name, last_name) values ('Lloyd', 'Wildin');
insert into employees (first_name, last_name) values ('Enrique', 'Garaway');
insert into employees (first_name, last_name) values ('Sansone', 'Gorst');
insert into employees (first_name, last_name) values ('Josepha', 'Lanning');
insert into employees (first_name, last_name) values ('Hermione', 'Sanzio');
insert into employees (first_name, last_name) values ('Trstram', 'Nicolson');
insert into employees (first_name, last_name) values ('Michail', 'Allderidge');
insert into employees (first_name, last_name) values ('Angelina', 'Pudden');
insert into employees (first_name, last_name) values ('Emmy', 'Lewknor');
insert into employees (first_name, last_name) values ('Bard', 'Lembcke');
insert into employees (first_name, last_name) values ('Shandra', 'Escoffrey');
insert into employees (first_name, last_name) values ('Conny', 'Denerley');
insert into employees (first_name, last_name) values ('Aldo', 'Mariault');
insert into employees (first_name, last_name) values ('Robin', 'Quantick');
insert into employees (first_name, last_name) values ('Hewett', 'Walaron');
insert into employees (first_name, last_name) values ('Marjorie', 'O''Toole');
insert into employees (first_name, last_name) values ('Witty', 'Ravillas');
insert into employees (first_name, last_name) values ('Josi', 'Frick');
insert into employees (first_name, last_name) values ('Bert', 'Lockner');
insert into employees (first_name, last_name) values ('Galvin', 'Folland');
insert into employees (first_name, last_name) values ('Elsi', 'Rudkin');
insert into employees (first_name, last_name) values ('Aindrea', 'Joffe');
insert into employees (first_name, last_name) values ('Briano', 'Ropp');
insert into employees (first_name, last_name) values ('Candis', 'Ahlf');
insert into employees (first_name, last_name) values ('Aleda', 'Blanning');
insert into employees (first_name, last_name) values ('Stefa', 'Goligher');
insert into employees (first_name, last_name) values ('Kellie', 'McCadden');
insert into employees (first_name, last_name) values ('Sindee', 'Dahle');
insert into employees (first_name, last_name) values ('Horton', 'Bidgood');
insert into employees (first_name, last_name) values ('Engelbert', 'Rangle');
insert into employees (first_name, last_name) values ('Dawn', 'Jevons');
insert into employees (first_name, last_name) values ('Van', 'MacGregor');
insert into employees (first_name, last_name) values ('Annalise', 'Wildsmith');
insert into employees (first_name, last_name) values ('Lezlie', 'Stallybrass');
insert into employees (first_name, last_name) values ('Siana', 'Yancey');
insert into employees (first_name, last_name) values ('Kate', 'Leiden');
insert into employees (first_name, last_name) values ('Engelbert', 'Ramsier');
insert into employees (first_name, last_name) values ('Killy', 'Lambert-Ciorwyn');
insert into employees (first_name, last_name) values ('Denney', 'Naisby');
insert into employees (first_name, last_name) values ('Florenza', 'Embery');
insert into employees (first_name, last_name) values ('Elston', 'Peacher');
insert into employees (first_name, last_name) values ('Janelle', 'Datte');
insert into employees (first_name, last_name) values ('Brendon', 'Joselson');
insert into employees (first_name, last_name) values ('Elaina', 'Slateford');
insert into employees (first_name, last_name) values ('Jeremy', 'Sinclar');
insert into employees (first_name, last_name) values ('Mauricio', 'Philp');
insert into employees (first_name, last_name) values ('Warden', 'Chadbourne');
insert into employees (first_name, last_name) values ('Morty', 'Colliar');
insert into employees (first_name, last_name) values ('Urbanus', 'Gamet');
insert into employees (first_name, last_name) values ('Sayre', 'Meere');
insert into employees (first_name, last_name) values ('Terrel', 'Teodorski');
insert into employees (first_name, last_name) values ('Lyndell', 'Zannotti');
insert into employees (first_name, last_name) values ('Niki', 'Ayrs');
insert into employees (first_name, last_name) values ('Terrie', 'Berthot');
insert into employees (first_name, last_name) values ('Wilone', 'Skittles');
insert into employees (first_name, last_name) values ('Tine', 'Bagge');
insert into employees (first_name, last_name) values ('Veda', 'Witheridge');
insert into employees (first_name, last_name) values ('Therine', 'Pardew');
insert into employees (first_name, last_name) values ('Marleah', 'Brydson');
insert into employees (first_name, last_name) values ('Mic', 'Van Dalen');
insert into employees (first_name, last_name) values ('Hastings', 'Osmon');
insert into employees (first_name, last_name) values ('Xylina', 'Thurstan');
insert into employees (first_name, last_name) values ('Roddy', 'Wedon');
insert into employees (first_name, last_name) values ('Jarred', 'Cleife');
insert into employees (first_name, last_name) values ('Toddie', 'Giovannilli');
insert into employees (first_name, last_name) values ('Eustacia', 'Brunet');
insert into employees (first_name, last_name) values ('Maxie', 'Redmire');
insert into employees (first_name, last_name) values ('Laural', 'Blankau');
insert into employees (first_name, last_name) values ('Annadiane', 'Flewitt');
insert into employees (first_name, last_name) values ('Agathe', 'Beeckx');
insert into employees (first_name, last_name) values ('Maureen', 'Dwane');
insert into employees (first_name, last_name) values ('Zelma', 'Kennaway');
insert into employees (first_name, last_name) values ('Dory', 'Glasser');
insert into employees (first_name, last_name) values ('Angus', 'Sollowaye');
insert into employees (first_name, last_name) values ('Marianna', 'Piddock');
insert into employees (first_name, last_name) values ('Minny', 'Downes');
insert into employees (first_name, last_name) values ('Ashleigh', 'Risbridger');
insert into employees (first_name, last_name) values ('Adella', 'Reggiani');
insert into employees (first_name, last_name) values ('Gaelan', 'Cyster');
insert into employees (first_name, last_name) values ('Caye', 'Yegorkin');
insert into employees (first_name, last_name) values ('Skipp', 'MacDuffie');
insert into employees (first_name, last_name) values ('Matty', 'Creus');
insert into employees (first_name, last_name) values ('Dal', 'Zorro');
insert into employees (first_name, last_name) values ('Kenny', 'Romans');
insert into employees (first_name, last_name) values ('Sharleen', 'Verbeke');
insert into employees (first_name, last_name) values ('Brigg', 'Messager');
insert into employees (first_name, last_name) values ('Donelle', 'Lorraway');
insert into employees (first_name, last_name) values ('Guenevere', 'Aleksankin');
insert into employees (first_name, last_name) values ('Leonora', 'Prinne');
insert into employees (first_name, last_name) values ('Codie', 'Hobble');
insert into employees (first_name, last_name) values ('Mattias', 'Nason');
insert into employees (first_name, last_name) values ('Avie', 'Dorning');
insert into employees (first_name, last_name) values ('Korella', 'Myhill');
insert into employees (first_name, last_name) values ('Brody', 'Tregale');
insert into employees (first_name, last_name) values ('Fania', 'Judgkins');
insert into employees (first_name, last_name) values ('Janessa', 'Sone');
insert into employees (first_name, last_name) values ('Madonna', 'Derrington');
insert into employees (first_name, last_name) values ('Hube', 'Prettjohn');
insert into employees (first_name, last_name) values ('Jeni', 'Simonyi');
insert into employees (first_name, last_name) values ('Bernice', 'Dimeloe');
insert into employees (first_name, last_name) values ('Josey', 'Kersting');
insert into employees (first_name, last_name) values ('Jeddy', 'Czajka');
insert into employees (first_name, last_name) values ('Merwin', 'Licas');
insert into employees (first_name, last_name) values ('Floyd', 'Self');
insert into employees (first_name, last_name) values ('Luther', 'Caswell');
insert into employees (first_name, last_name) values ('Jehu', 'Bresner');
insert into employees (first_name, last_name) values ('Natal', 'Hyams');
insert into employees (first_name, last_name) values ('Prisca', 'Ferrier');
insert into employees (first_name, last_name) values ('Binni', 'Bilham');
insert into employees (first_name, last_name) values ('Tod', 'Twycross');
insert into employees (first_name, last_name) values ('Wendel', 'Shedden');
insert into employees (first_name, last_name) values ('Ronny', 'Goodburn');
insert into employees (first_name, last_name) values ('Alyssa', 'Bottinelli');
insert into employees (first_name, last_name) values ('Dorita', 'Nilles');
insert into employees (first_name, last_name) values ('Conni', 'Pantlin');
insert into employees (first_name, last_name) values ('Halsy', 'Scud');
insert into employees (first_name, last_name) values ('Tuesday', 'Gagg');
insert into employees (first_name, last_name) values ('Vina', 'Dudley');
insert into employees (first_name, last_name) values ('Giovanni', 'Skeermor');
insert into employees (first_name, last_name) values ('Ninnetta', 'Bricknell');
insert into employees (first_name, last_name) values ('Aluino', 'Lavigne');
insert into employees (first_name, last_name) values ('Helen-elizabeth', 'Kersting');
insert into employees (first_name, last_name) values ('Marci', 'Schober');
insert into employees (first_name, last_name) values ('Charla', 'Sherborn');
insert into employees (first_name, last_name) values ('Julee', 'Calcut');
insert into employees (first_name, last_name) values ('Ingelbert', 'Vedyashkin');
insert into employees (first_name, last_name) values ('Sherilyn', 'Hodgins');
insert into employees (first_name, last_name) values ('Bidget', 'Helis');
insert into employees (first_name, last_name) values ('Salomo', 'Grinnov');
insert into employees (first_name, last_name) values ('Teddy', 'Ellingford');
insert into employees (first_name, last_name) values ('Keelby', 'Wanderschek');
insert into employees (first_name, last_name) values ('Catarina', 'Jonuzi');
insert into employees (first_name, last_name) values ('Renado', 'Streader');
insert into employees (first_name, last_name) values ('Cloris', 'Mallabar');
insert into employees (first_name, last_name) values ('Donia', 'Frake');
insert into employees (first_name, last_name) values ('Parke', 'McMichael');
insert into employees (first_name, last_name) values ('Helen', 'Ornelas');
insert into employees (first_name, last_name) values ('Tammi', 'Benda');
insert into employees (first_name, last_name) values ('Arabele', 'Hanaford');
insert into employees (first_name, last_name) values ('Marget', 'Camock');
insert into employees (first_name, last_name) values ('Hartley', 'Praten');
insert into employees (first_name, last_name) values ('Tiphani', 'Leek');
insert into employees (first_name, last_name) values ('Hashim', 'Baroch');
insert into employees (first_name, last_name) values ('Kipp', 'Heindrich');
insert into employees (first_name, last_name) values ('Toinette', 'William');
insert into employees (first_name, last_name) values ('Karim', 'Longega');
insert into employees (first_name, last_name) values ('Nancey', 'Hacquoil');
insert into employees (first_name, last_name) values ('Patrica', 'Yesipov');
insert into employees (first_name, last_name) values ('Zitella', 'Sandeford');
insert into employees (first_name, last_name) values ('Mart', 'Treadgold');
insert into employees (first_name, last_name) values ('Meryl', 'Danilovitch');
insert into employees (first_name, last_name) values ('Roby', 'Coath');
insert into employees (first_name, last_name) values ('Leupold', 'Livingstone');
insert into employees (first_name, last_name) values ('Rice', 'Bantick');
insert into employees (first_name, last_name) values ('Broderic', 'Snowding');
insert into employees (first_name, last_name) values ('Marnie', 'Domke');
insert into employees (first_name, last_name) values ('Kitti', 'Seabright');
insert into employees (first_name, last_name) values ('Joceline', 'Breddy');
insert into employees (first_name, last_name) values ('Rosanna', 'Seabourne');
insert into employees (first_name, last_name) values ('Martelle', 'Rubinsztein');
insert into employees (first_name, last_name) values ('Kipper', 'Golborne');
insert into employees (first_name, last_name) values ('Rickie', 'Pitrelli');
insert into employees (first_name, last_name) values ('Cymbre', 'Blanckley');
insert into employees (first_name, last_name) values ('Rozamond', 'Stathers');
insert into employees (first_name, last_name) values ('Nora', 'Rohlfs');
insert into employees (first_name, last_name) values ('Liuka', 'de Guise');
insert into employees (first_name, last_name) values ('Antonio', 'Reichelt');
insert into employees (first_name, last_name) values ('Borden', 'Elecum');
insert into employees (first_name, last_name) values ('Welbie', 'Horlick');
insert into employees (first_name, last_name) values ('Clementina', 'Hackelton');
insert into employees (first_name, last_name) values ('Coretta', 'Stening');
insert into employees (first_name, last_name) values ('Wright', 'Stonner');
insert into employees (first_name, last_name) values ('Davina', 'Schutt');
insert into employees (first_name, last_name) values ('Bud', 'Brogioni');
insert into employees (first_name, last_name) values ('Anabel', 'Buckell');
insert into employees (first_name, last_name) values ('Averil', 'Callis');
insert into employees (first_name, last_name) values ('Tessi', 'I''anson');
insert into employees (first_name, last_name) values ('Lynnelle', 'Rizzardo');
insert into employees (first_name, last_name) values ('Marylynne', 'Taffs');
insert into employees (first_name, last_name) values ('Amandy', 'de''-Ancy Willis');
insert into employees (first_name, last_name) values ('Vivi', 'Farrans');
insert into employees (first_name, last_name) values ('Jorrie', 'Paynter');
insert into employees (first_name, last_name) values ('Maggi', 'Casellas');
insert into employees (first_name, last_name) values ('Pavla', 'Broadberrie');
insert into employees (first_name, last_name) values ('Pietra', 'Lindhe');
insert into employees (first_name, last_name) values ('Idaline', 'Lorkings');
insert into employees (first_name, last_name) values ('Alonso', 'Filipowicz');
insert into employees (first_name, last_name) values ('Martin', 'Coit');
insert into employees (first_name, last_name) values ('Fanny', 'Pritchett');
insert into employees (first_name, last_name) values ('Consuelo', 'Illes');
insert into employees (first_name, last_name) values ('Hillary', 'Whiles');
insert into employees (first_name, last_name) values ('Bald', 'Baldacchi');
insert into employees (first_name, last_name) values ('Briney', 'Viant');
insert into employees (first_name, last_name) values ('Armando', 'Siderfin');
insert into employees (first_name, last_name) values ('Arluene', 'Englefield');
insert into employees (first_name, last_name) values ('Freddie', 'Zamorano');
insert into employees (first_name, last_name) values ('Alec', 'Sertin');
insert into employees (first_name, last_name) values ('Oliver', 'Ondrousek');
insert into employees (first_name, last_name) values ('Lorene', 'Milkins');
insert into employees (first_name, last_name) values ('Alonzo', 'Wasson');
insert into employees (first_name, last_name) values ('Tomas', 'Djekovic');
insert into employees (first_name, last_name) values ('Lesley', 'Grieves');
insert into employees (first_name, last_name) values ('Mellisa', 'Simunek');
insert into employees (first_name, last_name) values ('Tobit', 'Courvert');
insert into employees (first_name, last_name) values ('Michaela', 'Sitwell');
insert into employees (first_name, last_name) values ('Ado', 'Allbones');
insert into employees (first_name, last_name) values ('Louie', 'Harmar');
insert into employees (first_name, last_name) values ('Cassaundra', 'Jorck');
insert into employees (first_name, last_name) values ('Peri', 'Hurdle');
insert into employees (first_name, last_name) values ('Yoshiko', 'Lensch');
insert into employees (first_name, last_name) values ('Eudora', 'Roxbrough');
insert into employees (first_name, last_name) values ('Adam', 'Diggles');
insert into employees (first_name, last_name) values ('Adelina', 'Roycroft');
insert into employees (first_name, last_name) values ('Denys', 'Betke');
insert into employees (first_name, last_name) values ('Addia', 'Cawse');
insert into employees (first_name, last_name) values ('Ange', 'Tackley');
insert into employees (first_name, last_name) values ('Jase', 'Penhearow');
insert into employees (first_name, last_name) values ('Kerrie', 'O''Giany');
insert into employees (first_name, last_name) values ('Celene', 'Linneman');
insert into employees (first_name, last_name) values ('Adelina', 'Grayer');
insert into employees (first_name, last_name) values ('Mureil', 'Downs');
insert into employees (first_name, last_name) values ('Tim', 'Matousek');
insert into employees (first_name, last_name) values ('Caresa', 'Branno');
insert into employees (first_name, last_name) values ('Sharia', 'Defraine');
insert into employees (first_name, last_name) values ('Cly', 'Soame');
insert into employees (first_name, last_name) values ('Devina', 'Ciotti');
insert into employees (first_name, last_name) values ('Laughton', 'Heild');
insert into employees (first_name, last_name) values ('Jenn', 'Stickens');
insert into employees (first_name, last_name) values ('Othilie', 'Tockell');
insert into employees (first_name, last_name) values ('Tommie', 'O''Howbane');
insert into employees (first_name, last_name) values ('Willis', 'L''Episcopio');
insert into employees (first_name, last_name) values ('Micheil', 'Mantrip');
insert into employees (first_name, last_name) values ('Marcos', 'Willard');
insert into employees (first_name, last_name) values ('Natalee', 'Thieme');
insert into employees (first_name, last_name) values ('Honey', 'De Francisci');
insert into employees (first_name, last_name) values ('Bobbie', 'McIlreavy');
insert into employees (first_name, last_name) values ('Leanora', 'Tookill');
insert into employees (first_name, last_name) values ('Josselyn', 'Ebbens');
insert into employees (first_name, last_name) values ('Alyosha', 'Tippler');
insert into employees (first_name, last_name) values ('Antone', 'Ferne');
insert into employees (first_name, last_name) values ('Tod', 'Beaumont');
insert into employees (first_name, last_name) values ('Merralee', 'Patrick');
insert into employees (first_name, last_name) values ('Lorilyn', 'Vasic');
insert into employees (first_name, last_name) values ('Moore', 'Burgoine');
insert into employees (first_name, last_name) values ('Marjory', 'Ballchin');
insert into employees (first_name, last_name) values ('Blair', 'Barrat');
insert into employees (first_name, last_name) values ('Kit', 'Pursglove');
insert into employees (first_name, last_name) values ('Enrica', 'Issac');
insert into employees (first_name, last_name) values ('Adelle', 'Nickoll');
insert into employees (first_name, last_name) values ('Meier', 'Culshew');
insert into employees (first_name, last_name) values ('Winny', 'Bartol');
insert into employees (first_name, last_name) values ('Monroe', 'Heaney`');
insert into employees (first_name, last_name) values ('Vyky', 'Stoven');
insert into employees (first_name, last_name) values ('Yoko', 'Shemming');
insert into employees (first_name, last_name) values ('Tabbi', 'Bazell');
insert into employees (first_name, last_name) values ('Lindy', 'Campling');
insert into employees (first_name, last_name) values ('Danell', 'Threadgold');
insert into employees (first_name, last_name) values ('Riordan', 'Filby');
insert into employees (first_name, last_name) values ('Zandra', 'Lethardy');
insert into employees (first_name, last_name) values ('Latia', 'Entwhistle');
insert into employees (first_name, last_name) values ('Adelice', 'Collimore');
insert into employees (first_name, last_name) values ('Audry', 'Reubbens');
insert into employees (first_name, last_name) values ('Alayne', 'Pittoli');
insert into employees (first_name, last_name) values ('Jeanne', 'Winnister');
insert into employees (first_name, last_name) values ('Hettie', 'Brozsset');
insert into employees (first_name, last_name) values ('Rab', 'Janusik');
insert into employees (first_name, last_name) values ('Cal', 'Pitson');
insert into employees (first_name, last_name) values ('Jerrilyn', 'Plampeyn');
insert into employees (first_name, last_name) values ('Ardenia', 'Denidge');
insert into employees (first_name, last_name) values ('Arden', 'O''Hingerty');
insert into employees (first_name, last_name) values ('Lionel', 'Jewiss');
insert into employees (first_name, last_name) values ('Bowie', 'Borthram');
insert into employees (first_name, last_name) values ('Georgie', 'Marvin');
insert into employees (first_name, last_name) values ('Junia', 'Penke');
insert into employees (first_name, last_name) values ('Shurwood', 'Ferrelli');
insert into employees (first_name, last_name) values ('Dusty', 'Mennell');
insert into employees (first_name, last_name) values ('Marina', 'Peevor');
insert into employees (first_name, last_name) values ('Steward', 'Le Bosse');
insert into employees (first_name, last_name) values ('Sybila', 'Vodden');
insert into employees (first_name, last_name) values ('Julianne', 'Wickey');
insert into employees (first_name, last_name) values ('Kirby', 'Tivers');
insert into employees (first_name, last_name) values ('Carleton', 'Mariault');
insert into employees (first_name, last_name) values ('Carroll', 'Abrashkov');
insert into employees (first_name, last_name) values ('Rakel', 'Greensite');
insert into employees (first_name, last_name) values ('Penni', 'Starkey');
insert into employees (first_name, last_name) values ('Gerhardt', 'Nudde');
insert into employees (first_name, last_name) values ('Kassi', 'Wallman');
insert into employees (first_name, last_name) values ('Carlin', 'Limpenny');
insert into employees (first_name, last_name) values ('Rollo', 'Steer');
insert into employees (first_name, last_name) values ('Lenee', 'Howis');
insert into employees (first_name, last_name) values ('Lorianne', 'Portt');
insert into employees (first_name, last_name) values ('Holly', 'Cashell');
insert into employees (first_name, last_name) values ('Dagmar', 'Alekseicik');
insert into employees (first_name, last_name) values ('Saidee', 'Loving');
insert into employees (first_name, last_name) values ('Saloma', 'Trevan');
insert into employees (first_name, last_name) values ('Waylon', 'Lotte');
insert into employees (first_name, last_name) values ('Jennee', 'Thomas');
insert into employees (first_name, last_name) values ('Cordell', 'Smillie');
insert into employees (first_name, last_name) values ('Klara', 'Larciere');
insert into employees (first_name, last_name) values ('Saunder', 'Eastman');
insert into employees (first_name, last_name) values ('Sander', 'Stouther');
insert into employees (first_name, last_name) values ('Dorie', 'Waddicor');
insert into employees (first_name, last_name) values ('Drona', 'Lambrecht');
insert into employees (first_name, last_name) values ('Marje', 'Yesson');
insert into employees (first_name, last_name) values ('Kit', 'Mcsarry');
insert into employees (first_name, last_name) values ('Stefanie', 'Goodby');
insert into employees (first_name, last_name) values ('Koren', 'Escot');
insert into employees (first_name, last_name) values ('Umeko', 'Dulling');
insert into employees (first_name, last_name) values ('Cthrine', 'Garlic');
insert into employees (first_name, last_name) values ('Saw', 'Blinman');
insert into employees (first_name, last_name) values ('Whitney', 'Balaison');
insert into employees (first_name, last_name) values ('Stanleigh', 'Olenin');
insert into employees (first_name, last_name) values ('Raynor', 'Oyley');
insert into employees (first_name, last_name) values ('Jordanna', 'Luker');
insert into employees (first_name, last_name) values ('Kizzie', 'Saice');
insert into employees (first_name, last_name) values ('Sarine', 'Odgers');
insert into employees (first_name, last_name) values ('Lorri', 'Haughey');
insert into employees (first_name, last_name) values ('Hannis', 'Pittway');
insert into employees (first_name, last_name) values ('Ted', 'Sotheron');
insert into employees (first_name, last_name) values ('Francine', 'Durante');
insert into employees (first_name, last_name) values ('Eula', 'Frary');
insert into employees (first_name, last_name) values ('Chrystel', 'Feander');
insert into employees (first_name, last_name) values ('Fairlie', 'Skala');
insert into employees (first_name, last_name) values ('Susana', 'Woehler');
insert into employees (first_name, last_name) values ('Durante', 'Clemow');
insert into employees (first_name, last_name) values ('Vivienne', 'Facher');
insert into employees (first_name, last_name) values ('Donaugh', 'Jiruch');
insert into employees (first_name, last_name) values ('Bondon', 'Livard');
insert into employees (first_name, last_name) values ('Luelle', 'Boss');
insert into employees (first_name, last_name) values ('Tamara', 'Mothersole');
insert into employees (first_name, last_name) values ('Lilas', 'McCreery');
insert into employees (first_name, last_name) values ('Nell', 'Mealham');
insert into employees (first_name, last_name) values ('Ruddy', 'Danielli');
insert into employees (first_name, last_name) values ('Brandais', 'Booij');
insert into employees (first_name, last_name) values ('Kaela', 'Bussons');
insert into employees (first_name, last_name) values ('Liesa', 'Lawlee');
insert into employees (first_name, last_name) values ('Danika', 'Durnall');
insert into employees (first_name, last_name) values ('Clio', 'Whisson');
insert into employees (first_name, last_name) values ('Byron', 'Bouda');
insert into employees (first_name, last_name) values ('Edna', 'Winder');
insert into employees (first_name, last_name) values ('Hilde', 'Matisse');
insert into employees (first_name, last_name) values ('Adria', 'Scutter');
insert into employees (first_name, last_name) values ('Albie', 'Peckett');
insert into employees (first_name, last_name) values ('Chen', 'Order');
insert into employees (first_name, last_name) values ('Rosita', 'O''Gleasane');
insert into employees (first_name, last_name) values ('Rachel', 'Snaith');
insert into employees (first_name, last_name) values ('Evania', 'O''Loghlen');
insert into employees (first_name, last_name) values ('Lula', 'Archard');
insert into employees (first_name, last_name) values ('Georgianne', 'Berriball');
insert into employees (first_name, last_name) values ('Jaye', 'Ramstead');
insert into employees (first_name, last_name) values ('Luci', 'Frichley');
insert into employees (first_name, last_name) values ('Lonnie', 'Potier');
insert into employees (first_name, last_name) values ('Dory', 'Wakes');
insert into employees (first_name, last_name) values ('Lilli', 'Broddle');
insert into employees (first_name, last_name) values ('Aldwin', 'McKeowon');
insert into employees (first_name, last_name) values ('Crosby', 'McCarry');
insert into employees (first_name, last_name) values ('Anya', 'Frisch');
insert into employees (first_name, last_name) values ('Nesta', 'Hazeman');
insert into employees (first_name, last_name) values ('Orion', 'Vedyasov');
insert into employees (first_name, last_name) values ('Pennie', 'Casewell');
insert into employees (first_name, last_name) values ('Carol-jean', 'Measen');
insert into employees (first_name, last_name) values ('Titos', 'Bulch');
insert into employees (first_name, last_name) values ('Laurene', 'Vergo');
insert into employees (first_name, last_name) values ('Clea', 'Applegarth');
insert into employees (first_name, last_name) values ('Solly', 'Dimitrescu');
insert into employees (first_name, last_name) values ('Joeann', 'Roman');


-- LOAD DATA INFILE '/docker-entrypoint-initdb.d/data-seed.csv' INTO TABLE employees;

-- LOAD DATA LOCAL INFILE '/docker-entrypoint-initdb.d/data-seed.csv' INTO TABLE employees;
-- /docker-entrypoint-initdb.d/data-seed.csv
-- LOAD DATA LOCAL INFILE '/test.json' into table employees(jsondata);

-- INSERT INTO employees (first_name, last_name, department, email) VALUES ('Lorenz', 'Vanthillo', 'IT', 'lvthillo@mail.com');
