version: '2'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - C:\\Users\\Onur\\Desktop\\Projects\\o-bank\\services\\Utils\\kafka_connect_cassandra\\target\\kafka_connect_cassandra-1.0-package\\share\\java\\kafka_connect_cassandra:/opt/landoop/connectors/third-party/kafka-connect-file
    links:
      - cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - '5102:9042'



# 
# http://localhost:3030/logs/connect-distributed.log
# http://localhost:3030/kafka-connect-ui/#/cluster/fast-data-dev/connector/cassandraSinktest1
# connector.class=com.obank.kafka.connect.cassandra.OBankCassandraSinkConnector
# cassandra.url=cassandra
# value.converter.schema.registry.url=http://kafka-cluster:8081
# topics=test_topic
# cassandra.table=test_table
# value.converter.schemas.enable=false
# cassandra.port=9042
# cassandra.keyspace=test_keyspace
# value.converter=io.confluent.connect.avro.AvroConverter      