openapi: 3.0.0
info:
  title: o-bank Logger API
  description: Logger REST API for o-bank. This API has whole operations about logs which be consume by ui.<br>Developed in NodeJS (Express), Cassandra
  version: 1.0.0
  contact:
    name: Onur ÖZEL
    url: https://github.com/onur-ozel/o-bank
    email: onurozel41@gmail.com
  license:
    name: MIT License
    url: https://github.com/onur-ozel/o-bank/blob/master/LICENSE
tags:
  - name: Error
    description: Operations about error logs.
  - name: Performance
    description: Operations about performance logs.
paths:
  /logger/api/v1/error/{environment}:
    get:
      tags:
        - Error
      summary: Gets error logs
      description: Paging, sorting, searching and field filtering can be provided with query parameters.
      parameters:
        - $ref: '#/components/parameters/environment'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - allOf:
            - $ref: '#/components/parameters/sorts'
          example: +id,-lastModifiedDate
        - allOf:
            - $ref: '#/components/parameters/fields'
          example: sessionId,type,message
        - allOf:
            - $ref: '#/components/parameters/searches'  
          example: level[=]Error
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorLog'
        400:
          $ref: '#/components/responses/400InvalidRequest'
        500:
          $ref: '#/components/responses/500ApiError'
  /logger/api/v1/error/{id}:
    get:
      tags:
        - Error
      summary: Get error log by id.
      parameters:
        - $ref: '#/components/parameters/id'      
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorLog'
        400:
          $ref: '#/components/responses/400InvalidRequest'
        500:
          $ref: '#/components/responses/500ApiError'      
  
  /logger/api/v1/performance/{environment}:
    get:
      tags:
        - Performance
      summary: Gets performance logs
      description: Paging, sorting, searching and field filtering can be provided with query parameters.
      parameters:
        - $ref: '#/components/parameters/environment'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - allOf:
            - $ref: '#/components/parameters/sorts'
          example: +id,-lastModifiedDate
        - allOf:
            - $ref: '#/components/parameters/fields'
          example: sessionId,type,message
        - allOf:
            - $ref: '#/components/parameters/searches'  
          example: type[=]APIResponse
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerformanceLog'
        400:
          $ref: '#/components/responses/400InvalidRequest'
        500:
          $ref: '#/components/responses/500ApiError'
  /logger/api/v1/performance/{id}:
    get:
      tags:
        - Performance
      summary: Get performance log by id.
      parameters:
        - $ref: '#/components/parameters/id'      
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceLog'
        400:
          $ref: '#/components/responses/400InvalidRequest'
        500:
          $ref: '#/components/responses/500ApiError'    
components:
  schemas:
    ModelBase:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          description: Guid id.
          example: be5d9875-38d9-43be-86e7-9117ff3385d1 
        state:
          type: boolean
          readOnly: true
          description: Records valid or invalid state.
          example: true    
        sessionId:
          type: string
          readOnly: true
          description: Record created user session id.
          example: MVG9lKcPoNINVBIPJjdw1J9LLJbP_pqwoJYyuis 
        lastModifiedDate:
          type: string
          format: datetime
          readOnly: true
          description: Record last modification date time.
          example: '2018-08-17 02:44:22'      
    LogBase:
      type: object
      properties:
        environmentName:
          type: string
          description: Log environment. Customer.API, Mobile.Client etc.
          example: Customer.API   
        topic:
          type: string
          description: Log topic. Meaningful and trackable for handled logs. InvalidCustomerNumberException, AccountCreateTimeMeasurement, JavascriptError etc.
          example: AccountCreateTimeMeasurement           
    Error:
      allOf:
        - $ref: '#/components/schemas/ModelBase'
        - type: object
          properties:
            type:
              type: string
              description: Error type.
              example: NullPointerException
            code:
              type: string
              description: Error code.
              example: 12345
            level:
              type: string
              description: Error level.
              enum: [Error, Fatal, Warning, Info, Debug]
              example: Error   
            title:
              type: string
              description: User friendly error message title.
              example: Invalid Fields!.                     
            message:
              type: string
              description: User friendly error message.
              example: Invalid field name used in searching.
            stackTrace:
              type: string
              description: Error stack trace. It can be null for securtiy reasons.
            help:
              type: string
              description: Help url or instructions for taken error.    
    ErrorLog:
      allOf:
        - $ref: '#/components/schemas/ModelBase'
        - $ref: '#/components/schemas/LogBase'
        - type: object
          properties:
            type:
              type: string
              description: Error type.
              example: NullPointerException
            code:
              type: string
              description: Error code.
              example: 12345
            level:
              type: string
              description: Error level.
              enum: [Error, Fatal, Warning, Info, Debug]
              example: Error   
            title:
              type: string
              description: User friendly error message title.
              example: Invalid Fields!.                     
            message:
              type: string
              description: User friendly error message.
              example: Invalid field name used in searching.
            stackTrace:
              type: string
              description: Error stack trace. It can be null for securtiy reasons.
            help:
              type: string
              description: Help url or instructions for taken error.
    PerformanceLog:
      allOf:
        - $ref: '#/components/schemas/ModelBase'
        - $ref: '#/components/schemas/LogBase'
        - type: object
          properties:                  
            message:
              type: string
              description: User friendly message.
              example: Invalid field name used in searching.
            stackTrace:
              type: string
              description: Trace, name of method, code block which performance measurement is made.
              example: Invalid field name used in searching. 
            startTime:
              type: string
              format: datetime
              description: Measurement start time.
              example: '2018-08-17 02:44:22'   
            endTime:
              type: string
              format: datetime
              description: Measurement end time.
              example: '2018-08-17 02:44:22'   
            elapsedMiliSecond:
              type: int
              format: Int64
              description: Elapsed time in milisecond.
              example: 192939                                                                                                                               
  parameters:
    limit:
      name: limit
      in: query
      description: Limits return data count.
      required: false
      allowEmptyValue: true
      style: form
      explode: true
      example: 10
      schema:
        type: integer
        format: int32
        minimum: 1
    offset:
      name: offset
      in: query
      description: Offset data value.
      required: false
      allowEmptyValue: true
      style: form
      explode: true
      example: 0
      schema:
        type: integer
        format: int32
        minimum: 0
    sorts:
      name: sorts
      in: query
      description: Sort by columns. Multiple column can be provided by comma seperated. Use + for desc - for asc.
      required: false
      allowEmptyValue: true
      style: form
      explode: true
      example: +field_name1,-field_name2
      schema:
        type: string
    fields:
      name: fields
      in: query
      description: Filters result data with given field names. Multiple column can be provided by comma seperated.
      required: false
      allowEmptyValue: true
      style: form
      example: field_name1,field_name2
      schema:
        type: string
    searches:
      name: searches
      in: query
      description: Searches data with given conditions. Multiple column can be provided by comma seperated.<br>Operators can be used =, !=, >, <, >=, <=, % (like), !% (notlike), ^% (ends with), %^ (starts with), !^% (not ends with), !%^ (not starts with)
      required: false
      allowEmptyValue: true
      style: form
      example: field_name1[>=]250,field_name2[<]500
      schema:
        type: string        
    id:
      name: id
      in: path
      description: Unique id.
      required: true
      schema:
        type: string
        description: Guid id.
        example: be5d9875-38d9-43be-86e7-9117ff3385d1
    environment:
      name: environment
      in: path
      description: Log environment.
      required: true
      schema:
        type: string
        description: Log environment.
        enum: [Client, Server]
        example: Server      
  responses:
    500ApiError:
      description: API malfunction.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    400InvalidRequest:
      description: Invalid request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'