version: '3.4'
networks:
  obank.network:
    external:
      name: services_obank.network
services:
  logger.data:
    build:
      context: .
      dockerfile: Docker.Logger.Data.Cassandra.WithData.Dockerfile
    ports:
      - '5102:9042'
    networks: 
      - obank.network