version: "3.4"
services:
  parameter.cache.redis:
    image: redis:latest
    ports:
      - "6379:6379"
  parameter.data.mongo:
    build:
      context: .
      dockerfile: Docker.Parameter.Data.MongoDB.WithData.Dockerfile
    ports:
      - "27017:27017"
