version: "3.4"
services:
  customer.data:
    build:
      context: .
      dockerfile: Docker.Customer.Data.MSSql.WithData.Dockerfile
    ports:
      - "5101:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong_Passw0rd
      - MSSQL_PID=Developer
  customer.data.seed:
    build:
      context: .
      dockerfile: Docker.Customer.Data.MSSql.DataSeed.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    links:
      - customer.data
